// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTbP5OpXssmL6zqdZntdu-HTvuuVeykN0',
    appId: '1:279720491012:web:16e4ee22d3cac33ca91d51',
    messagingSenderId: '279720491012',
    projectId: 'app-thi-giua-ky',
    authDomain: 'app-thi-giua-ky.firebaseapp.com',
    databaseURL: 'https://app-thi-giua-ky-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-thi-giua-ky.firebasestorage.app',
    measurementId: 'G-MFM15BZEV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdSjqRz9yQLneXaMOvxNj83HgF3SsvFvs',
    appId: '1:279720491012:android:f97ee0c3bdf8c60aa91d51',
    messagingSenderId: '279720491012',
    projectId: 'app-thi-giua-ky',
    databaseURL: 'https://app-thi-giua-ky-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-thi-giua-ky.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgbStSDF4jcaVAUmx05Jr9SPC0iShXCqk',
    appId: '1:279720491012:ios:ded802b49cc48740a91d51',
    messagingSenderId: '279720491012',
    projectId: 'app-thi-giua-ky',
    databaseURL: 'https://app-thi-giua-ky-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-thi-giua-ky.firebasestorage.app',
    iosBundleId: 'com.apptienganh.vocabQuest',
  );
}
