/// 🌐 Bản dịch đơn giản cho màn Cài đặt (vi / en)
class AppLocalizations {
  static const Map<String, Map<String, String>> _strings = {
    'vi': {
      'settings_title': 'Cài đặt',
      'section_appearance': 'Giao diện',
      'section_sound': 'Âm thanh',
      'section_notification': 'Thông báo',
      'section_language': 'Ngôn ngữ',
      'section_info': 'Thông tin',
      'dark_mode': 'Chế độ tối',
      'dark_mode_sub': 'Giao diện thân thiện với mắt',
      'sound_effect': 'Hiệu ứng âm thanh',
      'sound_effect_sub': 'Âm thanh khi chơi game',
      'bg_music': 'Nhạc nền',
      'bg_music_sub': 'Phát nhạc khi mở app',
      'notification_reminder': 'Nhắc nhở học tập',
      'notification_reminder_sub': 'Nhắc bạn học mỗi ngày',
      'reminder_time': 'Giờ nhắc hàng ngày',
      'reminder_time_sub': 'Nhấn để đổi giờ nhắc',
      'language_label': 'Ngôn ngữ giao diện',
      'about_app': 'Về ứng dụng',
      'about_app_sub': 'Phiên bản',
      'rate_app': 'Đánh giá ứng dụng',
      'rate_app_sub': 'Cho chúng tôi 5 sao nhé!',
      'rate_app_thanks': 'Cảm ơn bạn đã đánh giá %d sao! ⭐',
      'rate_app_dialog_title': 'Đánh giá VocabQuest',
      'rate_app_dialog_sub': 'Bạn thấy ứng dụng thế nào?',
      'share_app': 'Chia sẻ ứng dụng',
      'share_app_sub': 'Giới thiệu cho bạn bè',
      'share_copied': 'Đã sao chép liên kết chia sẻ! 📋',
      'share_text':
          '📚 Học từ vựng cùng VocabQuest!\nTải ứng dụng tại: https://vocabquest.app',
      'logout': 'Đăng xuất',
      'logout_confirm': 'Bạn có chắc muốn đăng xuất không?',
      'cancel': 'Hủy',
      'close': 'Đóng',
      'save': 'Lưu',
      'choose_language': 'Chọn ngôn ngữ',
      'footer': 'Made with ❤️ by VocabQuest Team',
    },
    'en': {
      'settings_title': 'Settings',
      'section_appearance': 'Appearance',
      'section_sound': 'Sound',
      'section_notification': 'Notifications',
      'section_language': 'Language',
      'section_info': 'About',
      'dark_mode': 'Dark mode',
      'dark_mode_sub': 'Easier on the eyes',
      'sound_effect': 'Sound effects',
      'sound_effect_sub': 'In-game sound',
      'bg_music': 'Background music',
      'bg_music_sub': 'Play music when app opens',
      'notification_reminder': 'Learning reminder',
      'notification_reminder_sub': 'Remind me to study every day',
      'reminder_time': 'Daily reminder time',
      'reminder_time_sub': 'Tap to change reminder time',
      'language_label': 'App language',
      'about_app': 'About app',
      'about_app_sub': 'Version',
      'rate_app': 'Rate the app',
      'rate_app_sub': 'Give us 5 stars!',
      'rate_app_thanks': 'Thanks for your %d-star rating! ⭐',
      'rate_app_dialog_title': 'Rate VocabQuest',
      'rate_app_dialog_sub': 'How do you like the app?',
      'share_app': 'Share app',
      'share_app_sub': 'Tell your friends',
      'share_copied': 'Share link copied! 📋',
      'share_text':
          '📚 Learn vocabulary with VocabQuest!\nDownload: https://vocabquest.app',
      'logout': 'Log out',
      'logout_confirm': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'close': 'Close',
      'save': 'Save',
      'choose_language': 'Choose language',
      'footer': 'Made with ❤️ by VocabQuest Team',
    },
  };

  static String tr(String lang, String key) {
    return _strings[lang]?[key] ?? _strings['vi']![key] ?? key;
  }
}
